### ISSUE TITLE
[Feature Request] Worker enforcement of activity timeouts

### ISSUE THREAD

**Issue by bergundy** [temporalio/features#170]
Currently the only way for an activity to get notified that a timeout has expired (such as start-to-close) is by heartbeating.
The SDK throttles heartbeats and does not notify (`*`) the activity implementation that it should stop running since the server will reject the completion after timeout has expired.
While for sensitive workloads, there's no way around making activity implementations reentrant, adding the worker side timeout notification lowers the chance of duplicate activity executions.

A couple things worth noting:
- In the future the server might want to accept the activity after start-to-close timeout has expired assuming that it hasn't issued a new activity task to avoid needlessly losing the progress made by the activity (TODO: verify this is not supported today).
- We plan on adding an operator API to modify activity attributes such as timeouts, to support this properly, we would have to propagate the activity configuration to the worker running the activity

### Open questions
- Which timeouts would we want to notify the activity about?
  - start-to-close?
  - schedule-to-close?
  - heartbeat

(`*`) Apart from Go which sets a deadline on the context

### SDK specific implementation
- Go could cancel the context (it already does this today)
- Java would throw from heartbeat method
- Core based SDKs will propagate this via the per SDK cancellation mechanism

**Comment by Sushisource** [comment]
After a little discussion:

Re:
>API to modify activity attributes such as timeouts

As long as this modification only applies to the *next attempt* that's fine, that information can already be delivered via activity tasks. Something that changes the *current attempt*'s timeout would be an obnoxious new path which should be able to be sufficed by the normal existing cancel mechanisms (since the SDK would need to have a working connection to server already to receive the new timeouts).

* We should respect all 3 of the listed timeouts
* SDK does not reply to server w/ timeout (since by definition it should have already timed out server side and all we'd get is a "not found")
