### ISSUE TITLE
Create test containers from sdk-features for each SDK

### ISSUE THREAD

**Issue by bergundy** [temporalio/features#71]
Checklist:

- [x] Go
- [x] Java
- [x] TypeScript
- [x] Python

**Comment by bergundy** [comment]
We want to continuously test different SDK versions against Temporal Cloud and different OSS deployments to verify compatibility is maintained over time.

For that purpose, we should build a container from the sdk-feature test suite for each SDK version: `master`, latest release, previous X releases and use those containers for E2E testing.

**Comment by cretz** [comment]
I think instead we should make a container that will properly download whatever is needed and then run it instead of making separate containers. Can we make an issue to have the tool also work on commit hashes? I know exactly how I'd support commit hashes in all 4 of our SDK languages in this repo.

Then you have just one container for "sdk features" (updated as the features and harness are) and it's able to be run for any SDK lang and version or commit hash.

**Comment by bergundy** [comment]
As discussed during planning today, we'll build a separate container per SDK version but make sure to use the runner for downloading the SDK and building the docker image.
